package io.ferventio.app.ui

import android.content.Context
import android.content.res.Configuration
import android.os.LocaleList
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.remember
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.platform.LocalContext
import io.ferventio.app.R
import io.ferventio.app.domain.AppLanguage
import java.util.Locale

@Immutable
data class AppStrings(
    val settingsTitle: String,
    val settingsChatGroup: String,
    val settingsFeaturesGroup: String,
    val settingsDataGroup: String,
    val settingsAppGroup: String,
    val noAccount: String,
    val twitchAccount: String,
    val readOnlyChats: String,
    val signIn: String,
    val signOut: String,
    val messagesAndAppearance: String,
    val messagesAndAppearanceSummary: String,
    val inputAndBehavior: String,
    val inputAndBehaviorSummary: String,
    val userCard: String,
    val userCardSummary: String,
    val highlights: String,
    val highlightsSummary: String,
    val ignore: String,
    val ignoreSummary: String,
    val filterLanguage: String,
    val filterLanguageSummary: String,
    val notifications: String,
    val localHistory: String,
    val localHistorySummary: String,
    val imageCache: String,
    val imageCacheSummary: String,
    val exportAndSync: String,
    val exportAndSyncSummary: String,
    val diagnostics: String,
    val diagnosticsSummary: String,
    val aboutTitle: String,
    val aboutSummary: String,
    val aboutProjectTitle: String,
    val aboutProjectDescription: String,
    val aboutLinksTitle: String,
    val website: String,
    val websiteSummary: String,
    val github: String,
    val githubSummary: String,
    val telegramChannel: String,
    val telegramChannelSummary: String,
    val telegramChat: String,
    val telegramChatSummary: String,
    val translationProject: String,
    val translationProjectSummary: String,
    val localizationTitle: String,
    val appLanguage: String,
    val appLanguageSummary: String,
    val languageSystem: String,
    val languageRussian: String,
    val languageEnglish: String,
    val languagePageTitle: String,
    val languageSearchHint: String,
    val languageSystemSummary: String,
    val languageRussianSummary: String,
    val languageEnglishSummary: String,
    val languageSelected: String,
    val languageNoResults: String,
    val localizationFootnote: String,
    val legalInformation: String,
    val privacyPolicy: String,
    val openSourceLicenses: String,
    val openPublishedWebVersion: String,
    val localCrashReports: String,
    val localCrashReportsDescription: String,
    val exportReports: String,
    val deleteLocalReports: String,
    val privacyTitle: String,
    val licensesTitle: String,
    val moderationTitle: String,
    val moderationTimeout: String,
    val moderationWarn: String,
    val moderationBan: String,
    val moderationUnban: String,
    val moderationBlock: String,
    val moderationConfirm: String,
    val moderationCancel: String,
    val moderationReason: String,
    val moderationWarnTitleFormat: String,
    val moderationWarnSupportingText: String,
    val moderationBanTitleFormat: String,
    val moderationUnbanTitleFormat: String,
    val moderationBlockTitleFormat: String,
    val moderationBanBody: String,
    val moderationUnbanBody: String,
    val moderationBlockBody: String,
    val durationDaysFormat: String,
    val durationHoursFormat: String,
    val durationMinutesFormat: String,
    val durationSecondsFormat: String,
    val removeTimeoutPresetFormat: String,
)

@Composable
internal fun rememberAppStrings(appLanguage: AppLanguage): AppStrings {
    val context = LocalContext.current
    val configuration = LocalConfiguration.current
    val systemLocaleTags = configuration.locales.toLanguageTags()
    return remember(context, appLanguage, systemLocaleTags) {
        localizedContext(context, appLanguage).loadAppStrings()
    }
}

private fun localizedContext(context: Context, appLanguage: AppLanguage): Context {
    if (appLanguage == AppLanguage.SYSTEM) return context
    val configuration = Configuration(context.resources.configuration).apply {
        setLocales(LocaleList.forLanguageTags(appLanguage.storageValue))
        setLayoutDirection(Locale.forLanguageTag(appLanguage.storageValue))
    }
    return context.createConfigurationContext(configuration)
}

private fun Context.loadAppStrings(): AppStrings = AppStrings(
        settingsTitle = getString(R.string.ferventio_settings_title),
        settingsChatGroup = getString(R.string.ferventio_settings_chat_group),
        settingsFeaturesGroup = getString(R.string.ferventio_settings_features_group),
        settingsDataGroup = getString(R.string.ferventio_settings_data_group),
        settingsAppGroup = getString(R.string.ferventio_settings_app_group),
        noAccount = getString(R.string.ferventio_no_account),
        twitchAccount = getString(R.string.ferventio_twitch_account),
        readOnlyChats = getString(R.string.ferventio_read_only_chats),
        signIn = getString(R.string.ferventio_sign_in),
        signOut = getString(R.string.ferventio_sign_out),
        messagesAndAppearance = getString(R.string.ferventio_messages_and_appearance),
        messagesAndAppearanceSummary = getString(R.string.ferventio_messages_and_appearance_summary),
        inputAndBehavior = getString(R.string.ferventio_input_and_behavior),
        inputAndBehaviorSummary = getString(R.string.ferventio_input_and_behavior_summary),
        userCard = getString(R.string.ferventio_user_card),
        userCardSummary = getString(R.string.ferventio_user_card_summary),
        highlights = getString(R.string.ferventio_highlights),
        highlightsSummary = getString(R.string.ferventio_highlights_summary),
        ignore = getString(R.string.ferventio_ignore),
        ignoreSummary = getString(R.string.ferventio_ignore_summary),
        filterLanguage = getString(R.string.ferventio_filter_language),
        filterLanguageSummary = getString(R.string.ferventio_filter_language_summary),
        notifications = getString(R.string.ferventio_notifications),
        localHistory = getString(R.string.ferventio_local_history),
        localHistorySummary = getString(R.string.ferventio_local_history_summary),
        imageCache = getString(R.string.ferventio_image_cache),
        imageCacheSummary = getString(R.string.ferventio_image_cache_summary),
        exportAndSync = getString(R.string.ferventio_export_and_sync),
        exportAndSyncSummary = getString(R.string.ferventio_export_and_sync_summary),
        diagnostics = getString(R.string.ferventio_diagnostics),
        diagnosticsSummary = getString(R.string.ferventio_diagnostics_summary),
        aboutTitle = getString(R.string.ferventio_about_title),
        aboutSummary = getString(R.string.ferventio_about_summary),
        aboutProjectTitle = getString(R.string.ferventio_about_project_title),
        aboutProjectDescription = getString(R.string.ferventio_about_project_description),
        aboutLinksTitle = getString(R.string.ferventio_about_links_title),
        website = getString(R.string.ferventio_website),
        websiteSummary = getString(R.string.ferventio_website_summary),
        github = getString(R.string.ferventio_github),
        githubSummary = getString(R.string.ferventio_github_summary),
        telegramChannel = getString(R.string.ferventio_telegram_channel),
        telegramChannelSummary = getString(R.string.ferventio_telegram_channel_summary),
        telegramChat = getString(R.string.ferventio_telegram_chat),
        telegramChatSummary = getString(R.string.ferventio_telegram_chat_summary),
        translationProject = getString(R.string.ferventio_translation_project),
        translationProjectSummary = getString(R.string.ferventio_translation_project_summary),
        localizationTitle = getString(R.string.ferventio_localization_title),
        appLanguage = getString(R.string.ferventio_app_language),
        appLanguageSummary = getString(R.string.ferventio_app_language_summary),
        languageSystem = getString(R.string.ferventio_language_system),
        languageRussian = getString(R.string.ferventio_language_russian),
        languageEnglish = getString(R.string.ferventio_language_english),
        languagePageTitle = getString(R.string.ferventio_language_page_title),
        languageSearchHint = getString(R.string.ferventio_language_search_hint),
        languageSystemSummary = getString(R.string.ferventio_language_system_summary),
        languageRussianSummary = getString(R.string.ferventio_language_russian_summary),
        languageEnglishSummary = getString(R.string.ferventio_language_english_summary),
        languageSelected = getString(R.string.ferventio_language_selected),
        languageNoResults = getString(R.string.ferventio_language_no_results),
        localizationFootnote = getString(R.string.ferventio_localization_footnote),
        legalInformation = getString(R.string.ferventio_legal_information),
        privacyPolicy = getString(R.string.ferventio_privacy_policy),
        openSourceLicenses = getString(R.string.ferventio_open_source_licenses),
        openPublishedWebVersion = getString(R.string.ferventio_open_published_web_version),
        localCrashReports = getString(R.string.ferventio_local_crash_reports),
        localCrashReportsDescription = getString(R.string.ferventio_local_crash_reports_description),
        exportReports = getString(R.string.ferventio_export_reports),
        deleteLocalReports = getString(R.string.ferventio_delete_local_reports),
        privacyTitle = getString(R.string.ferventio_privacy_title),
        licensesTitle = getString(R.string.ferventio_licenses_title),
        moderationTitle = getString(R.string.ferventio_moderation_title),
        moderationTimeout = getString(R.string.ferventio_moderation_timeout),
        moderationWarn = getString(R.string.ferventio_moderation_warn),
        moderationBan = getString(R.string.ferventio_moderation_ban),
        moderationUnban = getString(R.string.ferventio_moderation_unban),
        moderationBlock = getString(R.string.ferventio_moderation_block),
        moderationConfirm = getString(R.string.ferventio_moderation_confirm),
        moderationCancel = getString(R.string.ferventio_moderation_cancel),
        moderationReason = getString(R.string.ferventio_moderation_reason),
        moderationWarnTitleFormat = getString(R.string.ferventio_moderation_warn_title_format),
        moderationWarnSupportingText = getString(R.string.ferventio_moderation_warn_supporting_text),
        moderationBanTitleFormat = getString(R.string.ferventio_moderation_ban_title_format),
        moderationUnbanTitleFormat = getString(R.string.ferventio_moderation_unban_title_format),
        moderationBlockTitleFormat = getString(R.string.ferventio_moderation_block_title_format),
        moderationBanBody = getString(R.string.ferventio_moderation_ban_body),
        moderationUnbanBody = getString(R.string.ferventio_moderation_unban_body),
        moderationBlockBody = getString(R.string.ferventio_moderation_block_body),
        durationDaysFormat = getString(R.string.ferventio_duration_days_format),
        durationHoursFormat = getString(R.string.ferventio_duration_hours_format),
        durationMinutesFormat = getString(R.string.ferventio_duration_minutes_format),
        durationSecondsFormat = getString(R.string.ferventio_duration_seconds_format),
        removeTimeoutPresetFormat = getString(R.string.ferventio_remove_timeout_preset_format),
)
